### ISSUE TITLE
Issue with MMDliB with my minecraft server

### ISSUE THREAD

**Issue by Pseudexe** [MinecraftModDevelopmentMods/MMDLib#55]
when i start my server it loads and crashes and the console says "[01:02:42] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MMDLib (mmdlib)
Caused by: java.lang.NumberFormatException: For input string: "0,02"" i don't know what to do with this, thanks for you help
![crash](https://user-images.githubusercontent.com/64444709/80430683-a11fd280-88ef-11ea-91db-0a62e1d186f6.PNG)

**Comment by jriwanek** [comment]
Show full logs, or atleast tell us *exactly* what versions of our mods that you're using, ideally both. We can't help you without that information.

**Comment by dshadowwolf** [comment]
Actually... Known issue - this is a bug in a bit of a hack to get around an issue where sometimes the system would display a repeating digit instead of the proper floating point number. The "parseFloat" method of the "Float" class is oddly not internationalized but the format routine that strips the value down to just two decimal places is.

This means that "Float.parseFloat()" expects a period for the decimal marker while a large number of European languages use a comma instead. A workaround is in [this issue](https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/407)

**Comment by jriwanek** [comment]
I'm pretty sure we pushed a fixed version after that issue @dshadowwolf, hence why I was asking what version the user was on.

**Comment by dshadowwolf** [comment]
True - current -dev has it fixed and the current release should have that as well... Guess I've just gotten so used to this class of issue I have the same response all the time.

**Comment by beamthelaser** [comment]
I am still getting this issue, and I am running rc2-36 straight off CurseForge.
https://pastebin.com/Pp9bvRWm

**Comment by dshadowwolf** [comment]
Then, to repeat - see [this issue](https://github.com/MinecraftModDevelopmentMods/BaseMetals/issues/407) for a workaround while we prepare for a new MMDLib release that will have a proper fix for this as part of the code.

**Comment by SirOMGitsYOU** [comment]
Is there any update on this situation - I'm using this workaround on my modpack, however, there has been no activity or updates for MMDLib to fix this problem ATLauncher doesn't allow me to amend the startup parameters and most people won't bother searching and will move on elsewhere.

**Comment by dshadowwolf** [comment]
Many apologies, but I have been completely buried by RL stuff and paying work - this tends to be a bit cyclical and my TODO for that side of things is shrinking rapidly, so I'll hopefully be able to focus on fixing this and some other issues that are holding up the -rc3 release.

**Comment by SirOMGitsYOU** [comment]
I have just had someone test your latest Ci Build and that seems to have fixed it. this one - https://ci.mcmoddev.com/job/MMDLib/job/MMDLib%201.12/48/artifact/build/libs/MMDLib-1.12-1.0.0-rc2.48.jar but it isn't present on Curseforge at the moment, is there any chance of it being uploaded?

**Comment by SirOMGitsYOU** [comment]
> Many apologies, but I have been completely buried by RL stuff and paying work - this tends to be a bit cyclical and my TODO for that side of things is shrinking rapidly, so I'll hopefully be able to focus on fixing this and some other issues that are holding up the -rc3 release.

I also just asked in CurseForge discord regarding using the development version in my modpack and they said They would need explicit permissions from you to allow it to be used due to the points on curseforge etc, Is that something you can possibly look at doing?

**Comment by dshadowwolf** [comment]
That'd be for @jriwanek to answer - she gets the points from this one. But I'm amenable to it.

**Comment by jriwanek** [comment]
Same

**Comment by SirOMGitsYOU** [comment]
> That'd be for @jriwanek to answer - she gets the points from this one. But I'm amenable to it.

Cool :) Hopefully, she will say yes as will help with getting my modpack working a little bit more stable lol

**Comment by jriwanek** [comment]
I just did.

**Comment by SirOMGitsYOU** [comment]
> I just did.

Ahh so you did I'm just blind then apparently, I've sent this to them in discord - however, unsure if they will accept this but hey ho will see.

**Comment by SirOMGitsYOU** [comment]
> I just did.

While that is all sorted out is there any possibility of uploading this build to CurseForge? https://ci.mcmoddev.com/job/MMDLib/job/MMDLib%201.12/48/artifact/build/libs/MMDLib-1.12-1.0.0-rc2.48.jar

**Comment by jriwanek** [comment]
fixed in dev
